# Generated by Django 4.0.6 on 2022-07-15 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_valorant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.IntegerField(choices=[(1, 'Pregunta'), (2, 'Problemas con cuenta'), (3, 'Recomendacion'), (5, 'Otro')])),
                ('correo', models.EmailField(max_length=100)),
                ('mensaje', models.TextField(max_length=500)),
            ],
        ),
    ]
