# Generated by Django 4.0.6 on 2022-07-15 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_valorant', '0004_creadores_alter_mapas_rango'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='asunto',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='creadores',
            name='agente_main',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='creadores',
            name='rango',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='mapas',
            name='agente',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='mapas',
            name='mapa',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='mapas',
            name='rango',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='user',
            name='pais',
            field=models.CharField(max_length=30),
        ),
    ]
